{
 "title": "DB2 Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "SQL Statements",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "SQL Statements" } },
   "targets": [
    {
     "expr": "sql_select_ratio{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_insert_ratio{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_update_ratio{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_delete_ratio{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_describe_ratio{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_prepare_ratio{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_open_ratio{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_close_ratio{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_merge_ratio{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_fetch_ratio{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_inserted_rows_ratio{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_updated_rows_ratio{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_deleted_rows_ratio{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_fetched_rows_ratio{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lock Manager Statistics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "total_suspends_ratio{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "deadlocks_ratio{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "lock_timeouts_ratio{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Address Space Statistics",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "ssas_tcb_time_seconds{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dsas_tcb_time_seconds{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "irlm_tcb_time_seconds{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ddf_tcb_time_seconds{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pre_srb_ssas_seconds{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pre_srb_dsas_seconds{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pre_srb_irlm_seconds{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pre_srb_ddf_seconds{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nonpre_srb_ssas_seconds{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nonpre_srb_dsas_seconds{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nonpre_srb_irlm_seconds{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nonpre_srb_irlm_seconds{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nonpre_srb_ddf_seconds{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pre_srb_ziip_ssas_seconds{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pre_srb_ziip_dsas_seconds{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pre_srb_ziip_irlm_seconds{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pre_srb_ziip_dist_seconds{service_name=\"DB31\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}