{
 "title": "Internal Telemetry Logs",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Internal Telemetry Logs (receivers)",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"otelcol-dev\"} | otelcol_component_kind = `receiver`"
    }
   ]
  },
  {
   "title": "Internal Telemetry Logs (processors)",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"otelcol-dev\"} | otelcol_component_kind = `processor`"
    }
   ]
  },
  {
   "title": "Internal Telemetry Logs (exporters)",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{service_name=\"otelcol-dev\"} | otelcol_component_kind = `exporter`"
    }
   ]
  }
 ]
}