services:

  init:
    image: busybox:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo-data:/var/tempo:Z

  tempo:
    image: grafana/tempo:main-bd4e88a
    hostname: tempo
    container_name: tempo
    restart: always
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tools/tempo.yml:/etc/tempo.yaml:Z
      - ./tempo-data:/var/tempo:Z
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "30317:4317"  # otlp grpc
      - "30318:4318"  # otlp http
    depends_on:
      - init
      
  prometheus:
    image: quay.io/prometheus/prometheus:v3.9.1
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus.yml
      - --web.enable-remote-write-receiver
    volumes:
      - ./config/tools/prometheus.yml:/etc/prometheus.yml:Z
    ports:
      - 9090:9090

  loki:
    image: grafana/loki:3.4.1
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/tools/loki-config.yaml:/etc/loki/local-config.yaml:Z

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./config/tools/grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:Z
      - ./config/tools/grafana/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:Z
      - ./dashboards:/var/lib/grafana/dashboards:Z
      - grafana-storage:/var/lib/grafana:Z
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor,alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
      - GF_INSTALL_PLUGINS=grafana-pyroscope-app
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo
      - loki

volumes:
  grafana-storage: {}
