{
 "title": "${DASH_TITLE}",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "promDataSource", "label": "Prometheus DataSource", "query": "prometheus" },
   { "name": "sysplex", "label": "SYSPLEX", "query": { "query": "label_values(zos_sysplex)" } },
   {
    "name": "system",
    "label": "SYSTEM",
    "query": {
     "query": "label_values({zos_sysplex=~\"$sysplex\"},service_namespace)"
    }
   },
   {
    "name": "subsystemName",
    "label": "Service",
    "query": {
     "query": "label_values({service_namespace=~\"$system\", zos_smf_id=~\".*CICS.*\"},service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Introduction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "options": {
    "content": "# Welcome\n\nThis sample dashboard provides monitoring of CICS subsystems.  \nPlease use the filters at the top to select:  \n- The Prometheus Data Source that contains the z/OS metrics  \n- The SYSPLEX that you are interested in  \n- The SYSTEM running on the previously selected SYSPLEX  \n- The Service (CICS region) running on the previously selected SYSTEM  \n\nThe values presented are auto-populated based on what is available to query"
   }
  },
  { "title": "Transaction Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Current Transactions vs Max Transaction Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "tran_pct_percent{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "Transaction Percentage - {{zos_smf_id}}"
    },
    {
     "expr": "tran_peak_pct_percent{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "Peak Transaction Percentage - {{zos_smf_id}}"
    }
   ]
  },
  {
   "title": "Max Transaction Count Hits",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "tran_times_at_mxt_ratio{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "Max Transaction Count Hits - {{zos_smf_id}}"
    }
   ]
  },
  {
   "title": "CPU Time Trends",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cp_cpu_time_microseconds{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "CP CPU Time - {{zos_smf_id}}"
    },
    {
     "expr": "off_cputime_microseconds{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "Off CPU Time - {{zos_smf_id}}"
    }
   ]
  },
  {
   "title": "Active Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "tran_total_active_ratio{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "Active Transactions - {{zos_smf_id}}"
    },
    {
     "expr": "tran_total_delayed_ratio{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "Delayed (Queued) Transactions - {{zos_smf_id}}"
    }
   ]
  },
  { "title": "Storage Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "UDSA Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "eudsa_dsa_used_by{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "EUDSA DSA Used - {{zos_smf_id}} - {{host_name}} - {{sysplex}}"
    },
    {
     "expr": "gudsa_dsa_used_by{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "GUDSA DSA Used - {{zos_smf_id}} - {{host_name}} - {{sysplex}}"
    },
    {
     "expr": "cusa_dsa_used_by{zos_sysplex=~\"$sysplex\", host_name=~\"$hostname\", service_name=~\"$subsystemName\"}",
     "legendFormat": "CUSA DSA Used - {{zos_smf_id}} - {{host_name}} - {{sysplex}}"
    }
   ]
  },
  {
   "title": "SDSA Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "esdsa_dsa_used_by{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "ESDSA DSA Used - {{zos_smf_id}}"
    },
    {
     "expr": "gsdsa_dsa_used_by{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "GSDSA DSA Used - {{zos_smf_id}}"
    }
   ]
  },
  {
   "title": "ECDSA Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "ecdsa_dsa_used_by{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "ECDSA DSA Used - {{zos_smf_id}}"
    }
   ]
  },
  {
   "title": "SOS",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sos_cnt_ratio{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "SOS Count - {{zos_smf_id}}"
    },
    {
     "expr": "sos_time_seconds{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "SOS Time - {{zos_smf_id}}"
    }
   ]
  },
  { "title": "Task Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "tasks_ratio{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "Tasks - {{zos_smf_id}}"
    },
    {
     "expr": "tasks_peak_ratio{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "Peak Tasks - {{zos_smf_id}}"
    }
   ]
  },
  {
   "title": "TCB CPU Secs",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 15, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tcb_cpu_sec_seconds{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "TCB CPU Seconds - {{zos_smf_id}}"
    }
   ]
  },
  {
   "title": "SRB CPU Secs",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 19, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "srb_cpu_sec_seconds{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "SRB CPU Seconds - {{zos_smf_id}}"
    }
   ]
  }
 ]
}