{
 "title": "${DASH_TITLE}",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "promDataSource", "label": "Prometheus DataSource", "query": "prometheus" },
   { "name": "sysplex", "label": "SYSPLEX", "query": { "query": "label_values(zos_sysplex)" } },
   {
    "name": "system",
    "label": "SYSTEM",
    "query": {
     "query": "label_values({zos_sysplex=~\"$sysplex\"},service_namespace)"
    }
   },
   {
    "name": "subsystemName",
    "label": "Service",
    "query": {
     "query": "label_values({service_namespace=~\"$system\", zos_smf_id=~\".*MQ.*\"},service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Introduction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "# Welcome\n\nThis sample dashboard provides monitoring of MQ subsystems.  \nPlease use the filters at the top to select:  \n- The Prometheus Data Source that contains the z/OS metrics  \n- The SYSPLEX that you are interested in  \n- The SYSTEM running on the previously selected SYSPLEX  \n- The Service (MQ Queue Manager) running on the previously selected SYSTEM  \n\nThe values presented are auto-populated based on what is available to query"
   }
  },
  { "title": "MQ Message Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Queue Manager Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "mqopen_requests_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "MQOPEN_REQUESTS"
    },
    {
     "expr": "mqclose_requests_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mqget_requests_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mqput_requests_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mqput1_requests_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mqinq_requests_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "MQ Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Queue Buffer Pools",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "buffers_in_pool_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "lowest_stealable_buffers_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "stealable_buffers_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "get_page_old_requests_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "get_page_new_requests_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dasd_read_operations_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "highest_depth_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "synchronous_write_operations_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "buffer_steals_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "MQ Queue Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Queue Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "current_depth_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "current_open_for_output_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "current_open_for_input_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oldest_message_age_seconds{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "short_term_qtime_microseconds{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "long_term_qtime_microseconds{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "highest_depth_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "lowest_depth_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mqput_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mqput1_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "successful_mqopen_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mqclose_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mqinq_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mqset_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "MQ Page Set", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Queue Page Set",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "total_pages_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "current_unused_pages_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "times_of_pageset_full_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "MQ Log Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Log Read Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "output_buff_logreads_satisfied_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "active_log_ds_reads_satisfied_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "archive_log_ds_reads_satisfied_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Write Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "write_request_count_nowait{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "write_request_count_force{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Manager Statistics",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unavailable_active_buffer_wait_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_bsds_access_requests_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "checkpoints_issued_count{zos_sysplex=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}