{
 "title": "CICS Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Transaction Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Transactions vs Max Transaction Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "tran_pct_percent{service_name=\"CICST31E\"}",
     "legendFormat": "Transaction Percentage - {{service_name}}"
    },
    {
     "expr": "tran_peak_pct_percent{service_name=\"CICST31E\"}",
     "legendFormat": "Peak Transaction Percentage - {{service_name}}"
    }
   ]
  },
  {
   "title": "Max Transaction Count Hits",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "tran_times_at_mxt_ratio{service_name=\"CICST31E\"}",
     "legendFormat": "Max Transaction Count Hits - {{service_name}}"
    }
   ]
  },
  {
   "title": "CPU Time Trends",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cp_cpu_time_microseconds{service_name=\"CICST31E\"}",
     "legendFormat": "CP CPU Time - {{service_name}}"
    },
    {
     "expr": "off_cputime_microseconds{service_name=\"CICST31E\"}",
     "legendFormat": "Off CPU Time - {{service_name}}"
    }
   ]
  },
  {
   "title": "Active Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "tran_total_active_ratio{service_name=\"CICST31E\"}",
     "legendFormat": "Active Transactions - {{service_name}}"
    },
    {
     "expr": "tran_total_delayed_ratio{service_name=\"CICST31E\"}",
     "legendFormat": "Delayed (Queued) Transactions - {{service_name}}"
    }
   ]
  },
  { "title": "Storage Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "UDSA Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "eudsa_dsa_used_by{service_name=\"CICST31E\"}",
     "legendFormat": "EUDSA DSA Used - {{service_name}}"
    },
    {
     "expr": "gudsa_dsa_used_by{service_name=\"CICST31E\"}",
     "legendFormat": "GUDSA DSA Used - {{service_name}}"
    },
    {
     "expr": "cusa_dsa_used_by{service_name=\"CICST31E\"}",
     "legendFormat": "CUSA DSA Used - {{service_name}}"
    }
   ]
  },
  {
   "title": "SDSA Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "esdsa_dsa_used_by{service_name=\"CICST31E\"}",
     "legendFormat": "ESDSA DSA Used - {{service_name}}"
    },
    {
     "expr": "gsdsa_dsa_used_by{service_name=\"CICST31E\"}",
     "legendFormat": "GSDSA DSA Used - {{service_name}}"
    }
   ]
  },
  {
   "title": "ECDSA Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "ecdsa_dsa_used_by{service_name=\"CICST31E\"}",
     "legendFormat": "ECDSA DSA Used - {{service_name}}"
    }
   ]
  },
  {
   "title": "SOS",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sos_cnt_ratio{service_name=\"CICST31E\"}",
     "legendFormat": "SOS Count - {{service_name}}"
    },
    {
     "expr": "sos_time_seconds{service_name=\"CICST31E\"}",
     "legendFormat": "SOS Time - {{service_name}}"
    }
   ]
  },
  { "title": "Task Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "tasks_ratio{service_name=\"CICST31E\"}",
     "legendFormat": "Tasks - {{service_name}}"
    },
    {
     "expr": "tasks_peak_ratio{service_name=\"CICST31E\"}",
     "legendFormat": "Peak Tasks - {{service_name}}"
    }
   ]
  },
  {
   "title": "TCB CPU Secs",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 15, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tcb_cpu_sec_seconds{service_name=\"CICST31E\"}",
     "legendFormat": "TCB CPU Seconds - {{service_name}}"
    }
   ]
  },
  {
   "title": "SRB CPU Secs",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 19, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "srb_cpu_sec_seconds{service_name=\"CICST31E\"}",
     "legendFormat": "SRB CPU Seconds - {{service_name}}"
    }
   ]
  }
 ]
}