{
 "title": "IMS Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Queue Pool Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of calls to QMGR ",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count_over_time(qp_qmgr_calls_ratio[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Queue Manager Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 8, "y": 1 },
   "targets": [
    { "expr": "qp_qmgr_locates_ratio", "legendFormat": "QP_QMGR_LOCATES" },
    { "expr": "qp_qmgr_releases_ratio", "legendFormat": "QP_QMGR_RELEASES" },
    { "expr": "qp_qmgr_loc_alters_ratio", "legendFormat": "QP_QMGR_LOC_ALTERS" },
    { "expr": "qp_purge_requests_ratio", "legendFormat": "QP_PURGE_REQUESTS" },
    { "expr": "qp_translate_req_ratio", "legendFormat": "QP_TRANSLATE_REQ " },
    { "expr": "qp_read_requests_ratio", "legendFormat": "QP_READ_REQUESTS" },
    { "expr": "qp_write_requests_ratio", "legendFormat": "QP_WRITE_REQUESTS" },
    { "expr": "qp_purge_writes_ratio", "legendFormat": "QP_PURGE_WRITES" },
    { "expr": "qp_purge_waits_ratio", "legendFormat": "QP_PURGE_WAITS" },
    { "expr": "qp_buffer_waits_ratio", "legendFormat": "QP_BUFFER_WAITS" },
    { "expr": "qp_decb_read_waits_ratio", "legendFormat": "QP_DECB_READ_WAITS" },
    { "expr": "qp_decb_writewaits_ratio", "legendFormat": "QP_DECB_WRITEWAITS" },
    { "expr": "qp_enqdeq_bfrwaits_ratio", "legendFormat": "QP_ENQDEQ_BFRWAITS" },
    { "expr": "qp_buffer_repos_ratio", "legendFormat": "QP_BUFFER_REPOS" },
    { "expr": "qp_msg_enqueues_ratio", "legendFormat": "QP_MSG_ENQUEUES" },
    { "expr": "qp_msg_dequeues_ratio", "legendFormat": "QP_MSG_DEQUEUES" }
   ]
  },
  {
   "title": "Buffer pool statistics ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 11 },
   "targets": [
    { "expr": "fbp_dir_io_count_ratio", "legendFormat": "FBP_DIR_IO_COUNT" },
    { "expr": "fbp_ifetch_req_ratio", "legendFormat": "FBP_IFETCH_REQ" },
    { "expr": "fbp_pfetch_req_ratio", "legendFormat": "FBP_PFETCH_REQ" },
    { "expr": "fbp_fblock_req_ratio", "legendFormat": "FBP_FBLOCK_REQ" },
    { "expr": "fbp_dir_no_entries_ratio", "legendFormat": "FBP_DIR_NO_ENTRIES" }
   ]
  },
  {
   "title": "Scheduling statistics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 21 },
   "targets": [
    { "expr": "sch_bmp_active_ratio", "legendFormat": "SCH_BMP_ACTIVE" },
    { "expr": "sch_mpp_active_ratio", "legendFormat": "SCH_MPP_ACTIVE" },
    { "expr": "sch_smb_pgm_confl_ratio", "legendFormat": "SCH_SMB_PGM_CONFL" },
    { "expr": "sch_smb_int_confl_ratio", "legendFormat": "SCH_SMB_INT_CONFL" },
    { "expr": "sch_smb_looked_at_ratio", "legendFormat": "SCH_SMB_LOOKED_AT" },
    { "expr": "sch_smb_other_ratio", "legendFormat": "SCH_SMB_OTHER" }
   ]
  },
  {
   "title": "Current log sequence number",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "logl_curr_seq_no_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logger statistics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 6, "y": 31 },
   "targets": [
    { "expr": "logl_awes_on_write_ratio", "legendFormat": "LOGL_AWES_ON_WRITE" },
    { "expr": "logl_chkw_requests_ratio", "legendFormat": "LOGL_CHKW_REQUESTS" },
    { "expr": "logl_wtwt_requests_ratio", "legendFormat": "LOGL_WTWT_REQUESTS" },
    { "expr": "phyl_olds_reads_ratio", "legendFormat": " PHYL_OLDS_READS" },
    { "expr": "phyl_olds_writes_ratio", "legendFormat": " PHYL_OLDS_WRITES" },
    { "expr": "phyl_wads_excpvr_ratio", "legendFormat": "PHYL_WADS_EXCPVR " }
   ]
  }
 ]
}