{
 "title": "DB2 Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "promDataSource", "label": "Prometheus DataSource", "query": "prometheus" },
   {
    "name": "sysplex",
    "label": "SYSPLEX",
    "query": {
     "query": "label_values({zos_smf_type=~\"zOS-IZOC_DB2_.*\"},zos_sysplex_name)"
    }
   },
   {
    "name": "system",
    "label": "SYSTEM",
    "query": {
     "query": "label_values({zos_sysplex_name=~\"$sysplex\", zos_smf_type=~\"zOS-IZOC_DB2_.*\"},service_namespace)"
    }
   },
   {
    "name": "subsystemName",
    "label": "Service",
    "query": {
     "query": "label_values({service_namespace=~\"$system\", zos_smf_type=~\"zOS-IZOC_DB2_.*\"},service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Introduction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "# Welcome\n\nThis sample dashboard provides monitoring of Db2 subsystems.  \nPlease use the filters at the top to select:  \n- The Prometheus Data Source that contains the z/OS metrics  \n- The SYSPLEX that you are interested in  \n- The SYSTEM running on the previously selected SYSPLEX  \n- The Service (Db2 subsystem) running on the previously selected SYSTEM  \n\nThe values presented are auto-populated based on what is available to query"
   }
  },
  { "title": "Db2 Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "SQL Statements",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "SQL Statements" } },
   "targets": [
    {
     "expr": "sql_select_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_insert_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_update_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_delete_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_describe_ratio{zos_sysplex_name=~\"$sysplex\", host_name=~\"$hostname\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_prepare_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_open_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_close_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_merge_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_fetch_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_inserted_rows_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_updated_rows_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_deleted_rows_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sql_fetched_rows_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lock Manager Statistics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "total_suspends_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "deadlocks_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "lock_timeouts_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Address Space Statistics",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "ssas_tcb_time_seconds{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dsas_tcb_time_seconds{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "irlm_tcb_time_seconds{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ddf_tcb_time_seconds{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pre_srb_ssas_seconds{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pre_srb_dsas_seconds{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pre_srb_irlm_seconds{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pre_srb_ddf_seconds{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nonpre_srb_ssas_seconds{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nonpre_srb_dsas_seconds{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nonpre_srb_irlm_seconds{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nonpre_srb_irlm_seconds{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nonpre_srb_ddf_seconds{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pre_srb_ziip_ssas_seconds{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pre_srb_ziip_dsas_seconds{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pre_srb_ziip_irlm_seconds{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pre_srb_ziip_dist_seconds{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\", service_name=~\"$subsystemName\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}