{
 "title": "IMS Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "promDataSource", "label": "Prometheus DataSource", "query": "prometheus" },
   {
    "name": "sysplex",
    "label": "SYSPLEX",
    "query": {
     "query": "label_values({zos_smf_type=~\"zOS-IZOC_IMS_.*\"},zos_sysplex_name)"
    }
   },
   {
    "name": "system",
    "label": "SYSTEM",
    "query": {
     "query": "label_values({zos_sysplex_name=~\"$sysplex\", zos_smf_type=~\"zOS-IZOC_IMS_.*\"},service_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Introduction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "# Welcome\n\nThis sample dashboard provides monitoring of IMS subsystems.  \nPlease use the filters at the top to select:  \n- The Prometheus Data Source that contains the z/OS metrics  \n- The SYSPLEX that you are interested in  \n- The SYSTEM running on the previously selected SYSPLEX  \n\nThe values presented are auto-populated based on what is available to query.  \n**Currently, the resulting metrics that each panel shows is an aggregate of all services (all IMS regions).**"
   }
  },
  { "title": "Queue Pool Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of calls to QMGR ",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "qp_qmgr_calls{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Manager Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "qp_qmgr_locates_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "QP_QMGR_LOCATES"
    },
    {
     "expr": "qp_qmgr_releases_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "QP_QMGR_RELEASES"
    },
    {
     "expr": "qp_qmgr_loc_alters_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "QP_QMGR_LOC_ALTERS"
    },
    {
     "expr": "qp_purge_requests_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "QP_PURGE_REQUESTS"
    },
    {
     "expr": "qp_translate_req_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "QP_TRANSLATE_REQ "
    },
    {
     "expr": "qp_read_requests_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "QP_READ_REQUESTS"
    },
    {
     "expr": "qp_write_requests_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "QP_WRITE_REQUESTS"
    },
    {
     "expr": "qp_purge_writes_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "QP_PURGE_WRITES"
    },
    {
     "expr": "qp_purge_waits_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "QP_PURGE_WAITS"
    },
    {
     "expr": "qp_buffer_waits_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "QP_BUFFER_WAITS"
    },
    {
     "expr": "qp_decb_read_waits_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "QP_DECB_READ_WAITS"
    },
    {
     "expr": "qp_decb_writewaits_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "QP_DECB_WRITEWAITS"
    },
    {
     "expr": "qp_enqdeq_bfrwaits_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "QP_ENQDEQ_BFRWAITS"
    },
    {
     "expr": "qp_buffer_repos_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "QP_BUFFER_REPOS"
    },
    {
     "expr": "qp_msg_enqueues_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "QP_MSG_ENQUEUES"
    },
    {
     "expr": "qp_msg_dequeues_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "QP_MSG_DEQUEUES"
    }
   ]
  },
  {
   "title": "Buffer pool statistics ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "fbp_dir_io_count_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "FBP_DIR_IO_COUNT"
    },
    {
     "expr": "fbp_ifetch_req_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "FBP_IFETCH_REQ"
    },
    {
     "expr": "fbp_pfetch_req_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "FBP_PFETCH_REQ"
    },
    {
     "expr": "fbp_fblock_req_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "FBP_FBLOCK_REQ"
    },
    {
     "expr": "fbp_dir_no_entries_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "FBP_DIR_NO_ENTRIES"
    }
   ]
  },
  {
   "title": "Scheduling statistics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sch_bmp_active_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "SCH_BMP_ACTIVE"
    },
    {
     "expr": "sch_mpp_active_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "SCH_MPP_ACTIVE"
    },
    {
     "expr": "sch_smb_pgm_confl_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "SCH_SMB_PGM_CONFL"
    },
    {
     "expr": "sch_smb_int_confl_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "SCH_SMB_INT_CONFL"
    },
    {
     "expr": "sch_smb_looked_at_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "SCH_SMB_LOOKED_AT"
    },
    {
     "expr": "sch_smb_other_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "SCH_SMB_OTHER"
    }
   ]
  },
  {
   "title": "Current log sequence number",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logl_curr_seq_no_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logger statistics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 6, "y": 40 },
   "targets": [
    {
     "expr": "logl_awes_on_write_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "LOGL_AWES_ON_WRITE"
    },
    {
     "expr": "logl_chkw_requests_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "LOGL_CHKW_REQUESTS"
    },
    {
     "expr": "logl_wtwt_requests_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "LOGL_WTWT_REQUESTS"
    },
    {
     "expr": "phyl_olds_reads_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": " PHYL_OLDS_READS"
    },
    {
     "expr": "phyl_olds_writes_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": " PHYL_OLDS_WRITES"
    },
    {
     "expr": "phyl_wads_excpvr_ratio{zos_sysplex_name=~\"$sysplex\", service_namespace=~\"$system\"}",
     "legendFormat": "PHYL_WADS_EXCPVR "
    }
   ]
  }
 ]
}